apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv-one
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow


  nfs:
    path: /nfsdata/PV0
    server: 10.0.0.192
