apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
   app: frontend
spec:
  volumes:
    - name: "web-data"
      hostPath:
        path: "/tmp/webserver"
  containers:
    - name: technologyupdate-app
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: "web-data"
      resources:
        requests:
          cpu: "40m"
          memory: "128Mi"
        limits:
          cpu: "50m"
          memory: "256Mi"
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
          
          
          
# Creating a webserver pod that will use host hard disk 
# to store its data. Data will be persistent and independent
# to the lifecycle of the pod. 
#
# The volume will be automaticatally created on the host
# where the pod is assigned by the scheduler.
#
# This pod definition also has memory and cpu limits
#
#
# run the pod
# kubectl create -f podvolume.yml
#
# check the pod
# kubectl get pods
#
# get details about pod
# kubectl describe pod/myapp
# {observe the mount location and node where its deployed}
#
# ssh onto the node where its deployed and go inside the pod
# kubectl exec -it myapp /bin/bash 
# if your code is having more than one container than please specify container name too
# kubectl exec -it myapp -c technologyupdate-app /bin/bash
# { go inside /var/www/html/ directory and create a file }
#
# exit from the pod and delete the pod
#
# delete pod
# kubectl delete pod/nnappone --namespace=learning
# 
# now again go inside the same node where the pod was running
# you will still find the file created inside /tmp/webserver/
# directory
#
