apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-one
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 150Mi
  storageClassName: slow
